---
- hosts: webserver
  become: true
  roles:
    - role: apache
      apache_create_vhosts: true
      apache_listen_ip: "*"
      apache_listen_port: 81

      apache_vhosts:
      - servername: "sei.devopsstore.local"
        serveradmin: "contato@devopsstore.com.br"
