---
- hosts: webserver
  become: true
  roles:
    - role: sei

  vars:
    source: "/etc/ansible/projects/ansible-sei/sources"

  environment:
    http_proxy: "http://proxy.mj.gov.br:3128"
    https_proxy: "http://proxy.mj.gov.br:3128"
    ftp_proxy: "http://proxy.mj.gov.br:3128"
    no_proxy: "localhost,127.0.0.1"
