---
# SEI Config
- name: Install SIP v3.0.0
  unarchive:
    src: "{{ source }}/sip/SIPv3.0.0.zip"
    dest: "/var/www/html"
    owner: apache
    group: apache

- name: Upgrade SIP v3.0.6
  unarchive:
    src: "{{ source }}/sip/SIPv3.0.6.zip"
    dest: "/var/www/html"
    owner: apache
    group: apache

# SIP Config
- name: Include SIP variables.
  include_vars: sip.yml

- name: Add SEI configuration.
  template:
    src: "{{ sip_configuracao_template }}"
    dest: "{{ sip_conf_path }}/{{ sip_configuracao_filename }}"
    owner: apache
    group: apache
    mode: 0644
  notify: restart apache
