---
dependencies: []

galaxy_info:
  author: devopsstore
  description: Apache 2.x for Linux.
  company: "devopsstore.com.br"
  license: "license (GNU)"
  min_ansible_version: 2.2
  platforms:
    - name: EL
      versions:
        - all
    - name: Amazon
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - precise
        - raring
        - saucy
        - trusty
        - xenial
    - name: Suse
      versions:
        - all
    - name: Solaris
      versions:
        - 11.3
  galaxy_tags:
    - web
    - apache
    - webserver
    - httpd
    - html

allow_duplicates: yes
