---
# SEI Config
- name: Install SEI v3.0.0
  unarchive:
    src: "{{ source }}/sei/v3.0.0.zip"
    dest: "/var/www/html"
    owner: apache
    group: apache

- name: Install HELP SEI v3.0.0
  unarchive:
    src: "{{ source }}/sei/ajuda.zip"
    dest: "/var/www/html/sei/web"
    owner: apache
    group: apache

- name: Upgrade SEI v3.0.6
  unarchive:
    src: "{{ source }}/sei/v3.0.6.zip"
    dest: "/var/www/html"
    owner: apache
    group: apache

- name: Include SEI variables.
  include_vars: sei.yml

- name: Add SEI configuration.
  template:
    src: "{{ sei_configuracao_template }}"
    dest: "{{ sei_conf_path }}/{{ sei_configuracao_filename }}"
    owner: apache
    group: apache
    mode: 0644

# SIP Config
- name: Include SIP variables.
  include_vars: sip.yml

- name: Add SEI configuration.
  template:
    src: "{{ sip_configuracao_template }}"
    dest: "{{ sip_conf_path }}/{{ sip_configuracao_filename }}"
    owner: apache
    group: apache
    mode: 0644
  notify: restart apache
